# Covid_ODE model configuration

data:
  age_mixing_matrix_term: data/polymod_normal_df.rds
  age_mixing_matrix_hol: data/polymod_no_school_df.rds
  mobility_matrix: data/movement.rds
  population_size: data/pop.rds
  commute_volume: data/commute_vol_2020-03-20.csv
  reported_cases: data/DailyConfirmedCases_2020-03-20.csv

parameter:
  beta1: 0.1  # R0 2.4
  beta2: 0.33  # Contact with commuters 1/3rd of the time
  omega: 1.0
  nu: 0.25
  gamma: 0.25

settings:
  inference_period:
    - 2020-02-19
    - 2020-02-21
  holiday:
    - 2020-03-23
    - 2020-10-01
  time_step: 1.
  prediction_period:
    - 2020-02-19
    - 2020-06-01

output:
  simulation: covid_ode.hd5
