# Covid_ODE model configuration

data:
  age_mixing_matrix_term: data/polymod_normal_df.rds
  age_mixing_matrix_hol: data/polymod_no_school_df.rds
  mobility_matrix: data/mergedflows.rds
  population_size: data/c2019modagepop.csv
  commute_volume: data/commute_vol_2020-03-27.csv
  reported_cases: data/DailyConfirmedCases_2020-04-18.csv

parameter:
  beta1: 0.6    # R0 2.4
  beta2: 0.33   # Contact with commuters 1/3rd of the time
  beta3: 1.0    # lockdown vs normal
  omega: 1.0    # Non-linearity parameter for commuting volume
  nu: 0.5      # E -> I transition rate
  gamma: 0.25   # I -> R transition rate
  I0: 4.0       # number of individuals at start of epidemic
  r: 10.0       # Negative binomial overdispersion parameter

settings:
  inference_period:
    - 2020-02-19
    - 2020-05-14
  holiday:
    - 2020-03-23
    - 2020-10-01
  lockdown:
    - 2020-03-23
    - 2020-10-01
  time_step: 1.
  prediction_period:
    - 2020-02-19
    - 2020-08-01

mcmc:
  dmax: %DMAX%
  nmax: %NMAX%
  m: %M%
  num_bursts: 100
  num_burst_samples: 100

output:
  posterior: tuning/%OUTPUTFILE%
  simulation: covid_ode.hd5
